<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>


  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\HLab.Avalonia\HLab.Base.Avalonia\HLab.Base.Avalonia.csproj" />
    <ProjectReference Include="..\..\HLab.Avalonia\HLab.Icons.Avalonia\HLab.Icons.Avalonia.csproj" />
    <ProjectReference Include="..\..\HLab.Avalonia\HLab.Localization.Avalonia3\HLab.Localization.Avalonia.csproj" />
    <ProjectReference Include="..\..\HLab.Avalonia\HLab.Mvvm.Avalonia\HLab.Mvvm.Avalonia.csproj" />
    <ProjectReference Include="..\..\HLab.Erp\HLab.Erp.Workflows\HLab.Erp.Workflows.csproj" />
  </ItemGroup>

</Project>
